spring:
  application:
    name: issue_management
  datasource:
    url: jdbc:mysql://localhost:3306/issue_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'